all: object move

object:
	@echo Creating the object file of graphic.c in ./Top/4
	@gcc -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c graphic.c

move:
	@echo Moving graphic.o from ./Top/4 to ./Top/obj
	@mv graphic.o ./../obj
